#ifndef H264E_H
#define H264E_H

#include <tizonia/OMX_Core.h>
#include <tizonia/OMX_Types.h>
#include <tizonia/OMX_Video.h>

#define OMX_VID_ENC_AVC_ROLE "video_encoder.avc"

/* With libtizonia, port indexes must start at index 0 */
#define OMX_VID_ENC_AVC_INPUT_PORT_INDEX 0
#define OMX_VID_ENC_AVC_OUTPUT_PORT_INDEX 1
#define OMX_VID_ENC_AVC_DEFAULT_FRAME_WIDTH 176
#define OMX_VID_ENC_AVC_DEFAULT_FRAME_HEIGHT 144
#define OMX_VID_ENC_AVC_INPUT_PORT_MIN_BUF_COUNT 8
#define OMX_VID_ENC_AVC_OUTPUT_PORT_MIN_BUF_COUNT 2
#define OMX_VID_ENC_AVC_PORT_MIN_INPUT_BUF_SIZE 4 * 1024
#define OMX_VID_ENC_AVC_PORT_MIN_OUTPUT_BUF_SIZE 345600
#define OMX_VID_ENC_AVC_PORT_NONCONTIGUOUS OMX_FALSE
#define OMX_VID_ENC_AVC_PORT_ALIGNMENT 0
#define OMX_VID_ENC_AVC_PORT_SUPPLIERPREF OMX_BufferSupplyInput

#define OMX_VID_ENC_BITRATE_MIN 64000
#define OMX_VID_ENC_BITRATE_MEDIAN 2000000
#define OMX_VID_ENC_BITRATE_MAX 240000000
#define OMX_VID_ENC_CONTROL_FRAME_RATE_DEN_DEFAULT 1001
#define OMX_VID_ENC_QUANT_I_FRAMES_DEFAULT 0x1c
#define OMX_VID_ENC_QUANT_P_FRAMES_DEFAULT 0x1c
#define OMX_VID_ENC_QUANT_B_FRAMES_DEFAULT 0x1c
#define OMX_VID_ENC_SCALING_WIDTH_DEFAULT 0xffffffff
#define OMX_VID_ENC_SCALING_HEIGHT_DEFAULT 0xffffffff
#define OMX_VID_ENC_IDR_PERIOD_DEFAULT 1000
#define OMX_VID_ENC_P_PERIOD_DEFAULT 3

OMX_PTR instantiate_h264e_config_port(OMX_HANDLETYPE ap_hdl);
OMX_PTR instantiate_h264e_input_port(OMX_HANDLETYPE ap_hdl);
OMX_PTR instantiate_h264e_output_port(OMX_HANDLETYPE ap_hdl);
OMX_PTR instantiate_h264e_processor(OMX_HANDLETYPE ap_hdl);

#endif                          /* H264E_H */
